services/horizon: Add Horizon API support for CAP 33
stellar/go pull request #2986
Opened 2020-09-09 15:24 UTC by tamirms

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Close https://github.com/stellar/go/issues/2862

Update Horizon responses to include sponsorship information. Also add endpoints for querying data by sponsorship.

- [x] Add attributes `num_sponsoring` and `num_sponsored` to accounts resource.

- [x] Add the attribute `sponsor to:

    - [x] `balances`
    - [x] `signers`
    - [x] `account`
    - [x] `account data `
        - [x] The sponsor will only be displayed when fetching the data object directly via /accounts/id/data/key
    - [x] `offers`
    - [x] `claimable_balances`

* Allow filtering by `sponsor` on the following resources:
    - [x] `/accounts?sponsor=accountID` returns all the accounts where the given `accountID` is sponsoring an account or any of its subentries.
    - [x] `/offers?sponsor=accountID` returns all offers where the given `accountID` is the sponsor.
    - [x] `/claimable_balances?sponsor=accountID` returns all claimable balances where the given `accountID` is the sponsor.

### Why

We need to extend the Horizon web API to expose CAP33 related data 

### Known limitations

[N/A]

2020-09-09 16:55 UTC, bartekn approved these changes

2020-09-09 16:55 UTC, bartekn commented on protocols/horizon/main.go
> +	Sponsor              string            `json:"sponsor,omitempty"`
I think `*string` and no `omitempty` make it more clear that it a ledger entry can have no sponsor, especially in `horizonclient`. Maybe let's discuss it quickly in Horizon meeting.

2020-09-09 16:55 UTC, bartekn commented on protocols/horizon/main.go
> -}
Good catch 👍

2020-09-09 16:55 UTC, bartekn commented on services/horizon/internal/actions/account.go
> +		}
We already have `countNonEmpty` for this (in `helpers.go`).

2020-09-09 18:05 UTC, abuiles requested changes

2020-09-09 18:05 UTC, abuiles commented on services/horizon/internal/actions/account.go
> +		records, err = historyQ.AccountsForSponsor(qp.Sponsor, pq)
@tamirms this is returning only the account entries where `qp.Sponsor` is a sponsor, but it should return all the accounts where `qp.Sponsor` is sponsoring the account entry or any of its subentries (trust lines,  signers, data, or account entry)

2020-09-10 20:13 UTC, abuiles approved these changes

2020-09-11 16:43 UTC, merged