Implement support for RevokeSponsorship in txnbuild
stellar/go pull request #3036
Opened 2020-09-17 22:03 UTC by 2opremio

Fixes #3001 .

It also fixes a small bug in `BeginSponsoringFutureReserves`

I am not too happy using pointers to represent a union type. If we only needed to build XDR operations, an interface would be enough. But since users need to be able to parse XDR (and inspect the structure) I don't see a much better approach.

*[Using an interface + type inspection](https://eli.thegreenplace.net/2018/go-and-algebraic-data-types/) is an option, but I don't think it's much better than representing the union type explicitly. On top of that, our users are probably used to the `xdr` package's approach which uses pointers.

* [Using a visitor pattern](https://making.pusher.com/alternatives-to-sum-types-in-go/) is safer, but unnecessarily complicated.

2020-09-17 22:06 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship_test.go
> +		t.Run(testcase.name, func(t *testing.T) {
We should probably have a test like this for all other operations (if so, the `BeginSponsoringFutureReserves` bug wouldn't have happened)

2020-09-18 12:15 UTC, abuiles requested changes
Looks good to me!  We need to change the `type ClaimableBalanceHash [32]byte` to the balance id (string) and we are good!

2020-09-18 12:15 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	ClaimableBalance *ClaimableBalanceHash
@2opremio the ledger key for claimable balance can be build with the ClaimableBalanceId -- so this should probably be string representing the ClaimableBalanceId (hex encoded)

And then we use `xdr.SafeUnmarshalHex()` to get the actual xdr struct

2020-09-18 12:15 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +type TrustLineId struct {
instead of adding a new struct, we could use `txnbuild.CreditAsset` or `txnbuild.Asset`  which is what we use in the create trustline operation.

2020-09-18 12:15 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +type TrustLineId struct {
Maybe the `CreditAsset` makes sense since `Asset` would allow `native`.

2020-09-18 12:15 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +		key.DataName = xdr.String64(r.Data.DataName)
I had a quick look it doesn't seem like we do in the other helpers -- however, I assume the xdr library will complain if you pass a bigger size.

2020-09-18 15:14 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +		key.DataName = xdr.String64(r.Data.DataName)
OK, good, I will review the TODO.

2020-09-18 15:18 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	ClaimableBalance *ClaimableBalanceHash
I am not sure about what you mean. are you referring to `xdr.ClaimableBalancerId`? Happy to use that directly, but at this point it just complicates the interface (`xdr.ClaimableBalancerId` is currently just a hash, with a  (as of now) redundant version field for backwards compatibility)

2020-09-18 15:21 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +type TrustLineId struct {
You mean, using the Asset issuer as the trustline address?

2020-09-18 15:46 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	ClaimableBalance *ClaimableBalanceHash
@2opremio I mean taking the balanceID as exposed by horizon. When you load a balance id, it has an ID which is something like `0000asdfasdf`, what I mean is receiving that ID instead of the Hash. 

Users should be able to build this operation with the data exposed by Horizon, with this version, you'll need to know how to go from Horizon's balanceID representation to ClaimableBalanceHash

2020-09-18 15:50 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +type TrustLineId struct {
nvm, we do need a new struct. 

So maybe the only change we need is the type for `Asset` to be `CreditAsset` since you can't have a trustline to native.

2020-09-18 15:51 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	OfferId              int64
can you check how do we expose this value in Horizon? I think we return OfferID as a string, so this should probably be a string too.

2020-09-18 18:57 UTC, Shaptic commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	Account          *string
This is likely a misunderstanding of how Go works, but why are these pointer types if they can't be `nil` (I see lots of `nil` checks below)?

2020-09-18 19:02 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	Account          *string
Only one isn't nil (that's the way we implement the sum type)

2020-09-18 19:14 UTC, 2opremio commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	OfferId              int64
I did, we return an `int64`:

https://github.com/stellar/go/blob/8d61d8e1d91c53e591eb2b673d54ad4614a87d5d/protocols/horizon/main.go#L237-L244

2020-09-18 19:41 UTC, abuiles commented on services/horizon/internal/txnbuild/revoke_sponsorship.go
> +	OfferId              int64
@2opremio thanks for checking! So we return it as a string, but  protocol converts it to int64. All good :)

2020-09-19 16:03 UTC, abuiles approved these changes

2020-09-19 19:39 UTC, merged