exp/services/recoverysigner: allow recoverysigner to sign transactions with CAP-33 BeginSponsoringFutureReserves operations
stellar/go pull request #3227
Opened 2020-11-16 17:02 UTC by marcelosalloum

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Allow recoverysigner to sign transactions with CAP-33 BeginSponsoringFutureReserves operations.

### Why

The validation below prevents recoverysigner from signing CAP-33 `BeginSponsoringFutureReserves` operations
https://github.com/stellar/go/blob/c2c77fb6066b7a06a0c31835039926ae7d9d3970/exp/services/recoverysigner/internal/serve/account_sign.go#L132-L138

For a `BeginSponsoringFutureReserves` operation we shouldn't be validating its account address but the sponsored id.

### Known limitations

N/A

2020-11-16 17:57 UTC, leighmcculloch requested changes
This change is not safe. See below.

2020-11-16 17:57 UTC, leighmcculloch commented on exp/services/recoverysigner/internal/serve/account_sign.go
> +			}
❗ This change is not safe to make.

This would allow any user get the server to sponsor their account using any other account on the recoverysigner because there is no validation of the operations source account.

To support CAP-33 we need to make the change described by stellar/stellar-protocol@1fa6d283e67674dae482c1e3c1f54b6a05691993, which is safer than the change being made here. Specifically the server must still validate the source account however it should expand the allowed values to include:
>an account the server knows definitively for the validity period of the transaction will not be authorized by the signing key

I suggest you take another approach to implementing this, by adding a configuration parameter that accepts a comma-separated list of account strkey's (i.e. `G...`), and if an account is in that list then any operation or transaction can have that value as their source account.

2020-11-17 14:44 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
> +OUTER:
It's my first time using labeled loops. From my research I didn't find anyone going against it so I'm assuming it's a valid approach. Please let me know if you think otherwise.

2020-11-17 14:45 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
> +			}
Thanks for the feedback, I adopted a new approach in https://github.com/stellar/go/pull/3227/commits/65865e4fc6ced1223a9e78ad69cbd0a93834ab3b using envs.

2020-11-17 18:03 UTC, leighmcculloch reviewed
Few things below I think we should change (❗ ), and then a question (❓ ) and suggestion (💡 ) about the use of labels, but up to you on the use of labels I think it is fine but I offer an alternative.

2020-11-17 18:29 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
>  		badRequest.Render(w)
Not really, that's not in my plans ATM.

2020-11-17 19:40 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
> +			l.Info("Operation's source account is not the request account nor any known CAP-33 authorized account.")
https://github.com/stellar/go/pull/3227/commits/bb8483fa709f1f1e143daf8c64400b7eb13fe018

2020-11-17 19:40 UTC, marcelosalloum commented on exp/services/recoverysigner/cmd/serve.go
> +			Usage:     "A comma-separated list of accounts that are not authorized by the signing key and are accepted as source account when signing transactions",
https://github.com/stellar/go/pull/3227/commits/bb8483fa709f1f1e143daf8c64400b7eb13fe018

2020-11-17 19:40 UTC, marcelosalloum commented on exp/services/recoverysigner/cmd/serve.go
> +			Name:      "cap33-allowed-source-accounts",
https://github.com/stellar/go/pull/3227/commits/bb8483fa709f1f1e143daf8c64400b7eb13fe018

2020-11-17 19:55 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/serve.go
> +	cap33AllowedSourceAccounts := strings.Split(opts.CAP33AllowedSourceAccounts, ",")
https://github.com/stellar/go/pull/3227/commits/a38a1108fd8f741a574efabc4d9fe3f23f0853d3

2020-11-17 19:56 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
> +					SourceAccount: &txnbuild.SimpleAccount{AccountID: "GDR3RJVOHYR5A4RSLZ7D3GOSTPBGD2FY7KJD7ZB7363ROOQHWYDVVULS"},
I kind of did that at the bottom of the test but I agree having a whole different test function is clearer, I'll do as you suggested 😄 .

2020-11-17 20:30 UTC, leighmcculloch commented on exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
> +					SourceAccount: &txnbuild.SimpleAccount{AccountID: "GDR3RJVOHYR5A4RSLZ7D3GOSTPBGD2FY7KJD7ZB7363ROOQHWYDVVULS"},
Ah I missed that. Yes, different tests for different use cases. Tests communicate your intent to readers, and bundling tests into one test doesn't tell a clear story. Thanks!

2020-11-17 20:50 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign_signing_address_test.go
> +					SourceAccount: &txnbuild.SimpleAccount{AccountID: "GDR3RJVOHYR5A4RSLZ7D3GOSTPBGD2FY7KJD7ZB7363ROOQHWYDVVULS"},
Agreed! I evolved it into 2 tests in https://github.com/stellar/go/pull/3227/commits/a38a1108fd8f741a574efabc4d9fe3f23f0853d3

2020-11-17 20:52 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
>  			return
Yep, I wasn't sure about using labels and I prefer to lean towards the project syntax rather than creating a non-orthodox approach. I'll update it to drop the use of the label.

2020-11-17 20:57 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
>  			return
https://github.com/stellar/go/pull/3227/commits/c9db999435658d87358eb2e879364ab53bb82715

2020-11-17 20:59 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/account_sign.go
> +OUTER:
Ended up stopping using labels in https://github.com/stellar/go/pull/3227/commits/c9db999435658d87358eb2e879364ab53bb82715.

2020-11-17 22:04 UTC, leighmcculloch approved these changes
Two things that I think needs changing (❗) and one thing that is just an FYI and not required (💡).

❗ Could you update the README to reference and link to the latest version of the SEP-30 so that it is clear from the readme that it supports the latest version now?

https://github.com/stellar/go/blob/b361462084910cdd934ad8b69cf4a85c2c610b63/exp/services/recoverysigner/README.md#L3-L4

https://github.com/stellar/go/blob/b361462084910cdd934ad8b69cf4a85c2c610b63/exp/services/recoverysigner/README.md#L77


Otherwise this looks great!

2020-11-18 10:31 UTC, marcelosalloum commented on exp/services/recoverysigner/internal/serve/serve.go
> +	var allowedSourceAccounts []*keypair.FromAddress
https://github.com/stellar/go/pull/3227/commits/36e559a63fe5a612eb547f6ad709cf9e2cfb68cf

2020-11-18 10:45 UTC, marcelosalloum commented
> ❗ Could you update the README to reference and link to the latest version of the SEP-30 so that it is clear from the readme that it supports the latest version now?

Sure, done it in https://github.com/stellar/go/pull/3227/commits/92034282c99041c25e7b67f68f950713d9d63968.

2020-11-18 20:35 UTC, merged