#4170: added skeleton of new asset filter
stellar/go pull request #4187
Opened 2022-01-18 21:12 UTC by sreuland

2022-01-19 18:32 UTC, 2opremio commented on services/horizon/internal/ingest/filters/asset_filter.go
> +	traverseOperationsList []string
I would keep it simple to start with and hardcode what you think is most reasonable.

2022-01-19 19:03 UTC, sreuland commented on services/horizon/internal/ingest/filters/asset_filter.go
> +	traverseOperationsList []string
yes, I just added commit for filter params as json file also, to consider as light(er) weight middle ground between cli which is untenable as you mention and the db persistence for params.

2022-01-19 23:55 UTC, sreuland commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
@2opremio , on the filter interface, I'm wondering, is the tx level a bit too course grained, this will result in dropping  operations in the tx that have no relevance to the filter? wondering if the the filter method interface should work a bit lower at the Operation level, like:

```
func FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) ([]*xdr.Operation, error) 
```

2022-01-20 16:46 UTC, 2opremio commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
You are bring up a  really good point which, as you have problably seen, I incorporated to the design doc.

Since we are not sure what's the best granularity, I think it's better to keep it simple. Filtering whole transactions is arguably simpler.

However, if you have any examples in which full-transaction filtering doesn't make sense, please share them. That may justify going for finer granularity right away.

2022-01-20 18:12 UTC, sreuland commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
Ok, it looks like like two effects from filtering at tx level emerge:

the first appears to be a net effect that would include additional operations that didn't match the filter intent, i.e. if an asset filter rule is for '3', and a TX comes in like this:
```
tx {
   opPayment: (Asset:1)
   opPayment: (Asset:2)
   opPathPayment: (SendAsset:2, DestAsset:3)
   opPathPayment: (SendAsset:4, DestAsset:5)
}
```

then the the asset filter would return `true` and the other ops with non-filtered assets would still get persisted, making the space saving aspect of the filter less effective. 

the second effect of filtering at tx level appears to be in case of asset filter could cause dropping op data that has nothing to do with filtered assets, i.e. if a tx has no ops that contained a whitelisted asset, then the asset filter returns `false` triggering the tx to be dropped, but it may have other non-filtered asset related ops data that should continue to be persisted , such as if asset filter rule is for '5', and this tx comes in:

```
tx {
   opPayment: (Asset:1)
   opPathPayment: (SendAsset:2, DestAsset:3)
   opMergeAcct: (Acct:1234)
   opSponsoring: (Acct:5555)
}
```

the asset filter returns `false`, and the other non-asset relevant ops like the acct ops, would get dropped. 

maybe for first pass on poc, we don't need to address this yet, just so we can start seeing some rough numbers or if we should consider getting the filter integrated at the ops level up front.

2022-01-20 18:31 UTC, sreuland commented
@2opremio , would like to get your opinion on a possible design change for accessing filters as a static singleton rather than constructing it in processor_runner.go, processors that want to be filter-aware, can invoke `filters.ProcessFilters(operation)` directly:
![filter_ops_flow](https://user-images.githubusercontent.com/10703845/150399046-37083c29-bb51-45f8-b755-90fd0607d1a4.png)

2022-01-21 10:45 UTC, 2opremio commented
> [edit] - nvm, I see processor_runner using a creational pattern per ledger for processors with`processor_runner:buildTransactionProcessor()`, and filters following the same pattern, so, looks consistent to follow that. The filters will at some point be parsing config parameters for rules during instantiation, may be some optimization on that later.

👍

2022-01-21 10:59 UTC, 2opremio commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
> then the the asset filter would return `true` and the other ops with non-filtered assets would still get persisted, making the space saving aspect of the filter less effective.

Good point. This is extensible to accounts as well.

From the usability standpoint, I think it really depends on how transactions are used and giving a consistent view from Horizon.

1. I think that in many cases transactions only make sense as a unit (e.g. sponsoring sandwich), even if you are only whitelisting certain accounts/assets in the transaction.
2. Also, only including certain operations from a transaction will result in information gaps when obtaining information about the transaction (effects, participants etc ... ). Admittedly, the same happens at the  transaction->ledger level, but end users don't produce ledgers, they submit full transactions. So I think it's less aggressive to partially omit ledger->transaction relationships than transaction->operation ones.

From the performance standpoint, it totally makes sense to have a finer granularity (resulting in larger storage savings). So we will have to see.

2022-01-21 11:09 UTC, 2opremio commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
> the second effect of filtering at tx level appears to be in case of asset filter could cause dropping op data that has nothing to do with filtered assets,

That's a really really good point. This doesn't really apply to accounts (since all operations are account-related).

I think that, as a user, I may be surprised about operations `opMergeAcct: (Acct:1234), opSponsoring: (Acct:5555)` being dropped.

The current asset filter implementation only makes sense for users who *only* care about asset operations. This may be too strict to be generally useful, I am not sure.

I don't really have a good solution for this, though. If users want to keep track of asset-unrelated operations while whitelisting assets, we will probably need operation-level filtering.

2022-01-21 17:44 UTC, sreuland commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
> The current asset filter implementation only makes sense for users who only care about asset operations. This may be too strict to be generally useful, I am not sure.

> I don't really have a good solution for this, though. If users want to keep track of asset-unrelated operations while whitelisting assets, we will probably need operation-level filtering.

@jcx120 , any insights from product/user standpoint on this type of effect from asset filtering, pls let us know, thanks!

2022-01-24 02:05 UTC, sreuland commented on services/horizon/internal/db2/schema/migrations/53_whitelists.sql
> +CREATE TABLE filter_config (
@2opremio ,just thinking out loud on filter config aspects, such as generic filter config schema, example - https://github.com/stellar/go/pull/4187/files#diff-060057b3a0aa48e8d48274558827e83c7c4ded5edb0a416fc5b9eebaa32882d1

rather than exposing config from http API , which requires some security to restrict access, what if we used`horizon db` subcommand like `horizon db config filter` to display to console and `horizon db config filter load <json_file_path>`, which only a sysadmin will have access at that cli level. 

the user can define filer rules before ingestion starts, such as`horizon db init` and then `horizon db config filter load myfilters.json` could be done before`horizon serve ....` and afterwards to update per the filter config cacheing behavior ideas.

2022-01-24 17:19 UTC, sreuland commented on services/horizon/internal/httpx/router.go
> +		NoStateVerification: config.IngestDisableStateVerification,
it looked like `DisableStateVerification` was intentionally left off the config, as i noticed `--ingest-disable-state-verification=true` had no effect from command line, was getting `Still ingesting` so, I added it in here, just to get it working in local runtime tests, but can remove this was not meant to be enabled.

2022-01-25 20:06 UTC, 2opremio requested changes

2022-01-25 20:06 UTC, 2opremio commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
Can you make the file layout consistent with the account filtering? (i e. Either move account filtering to this directory or remove the directory)

2022-01-25 20:06 UTC, 2opremio commented on services/horizon/internal/ingest/processor_runner.go
> +			// this is example asset filter config by list of assets that were
Can you add a TODO about making this configurable?

2022-01-25 20:41 UTC, sreuland commented on services/horizon/internal/ingest/filters/asset_filter.go
> +func (f *AssetFilter) FilterTransaction(ctx context.Context, transaction ingest.LedgerTransaction) (bool, error) {
yes, had to make processors.ParticipantsForTransaction public, [79c777311c04](https://github.com/stellar/go/pull/4187/commits/79c777311c04b71827482837dfc25819273ecc50)

2022-01-26 00:28 UTC, 2opremio commented on services/horizon/internal/db2/history/account_filter_whitelist.go
> +// TODO - is this needed, currently not referenced, static check?
Let's remove this!

2022-01-26 17:13 UTC, merged