Migrate the rest of the CircleCI jobs to GitHub Actions
stellar/go pull request #4250
Opened 2022-02-28 23:41 UTC by 2opremio

Closes  #4242

2022-03-01 03:50 UTC, leighmcculloch commented
@2opremio I see your commits:
- [See why the current PR commit is missing](https://github.com/stellar/go/pull/4250/commits/05e96e38d70b048bee40833938d60ad3a72608df)
- [It turns out that GITHUB_SHA is not equivalente to CIRCLE_SHA1](https://github.com/stellar/go/pull/4250/commits/c89957ee4ca6aa2b9fd44223306ed77a62a026c1)

I recently went through this pain adding docker image publishing to stellar/quickstart and ran into the same thing. If you want to take a look at the workflows there, checkout:
- https://github.com/stellar/quickstart/blob/5d478fb/.github/workflows/Dockerfile.yml#L18
- https://github.com/stellar/quickstart/blob/5d478fb/.github/workflows/Dockerfile.dev.yml
- https://github.com/stellar/quickstart/blob/5d478fb/.github/actions/push/action.yml

GitHub PRs run Github Actions on a commit that has the master branch merged into the PR's latest commit. So `github.sha` and `GITHUB_SHA` are not the PR's latest commit, they are a merge commit that includes the master branch.

If you want to prevent this from happening, you need to do two things:

1. Use `github.event.pull_request.head.sha` in PRs wherever you need the sha, instead of `github.sha`. E.g.:
   ```
   env:
     HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
   ```
   See this for an example: https://github.com/stellar/quickstart/blob/5d478fb/.github/workflows/Dockerfile.yml#L18

2. Checkout the last commit in the PR rather than checkout the default commit the action runs with:
   ```
       - uses: actions/checkout@v2
         with:
           ref: ${{ env.HEAD_SHA }}
   ```

Given you're making a workflow that's designed to run on tagged releases, none of this might matter.

2022-03-01 03:52 UTC, leighmcculloch reviewed
🎉

2022-03-01 10:54 UTC, 2opremio commented
> I recently went through this pain adding docker image publishing to stellar/quickstart and ran into the same thing

Yes, that's really annoying. It turns out that, for PRs, `github.ref` points to `refs/pull/<PR_number>/merge` instead of `refs/pull/<PR_number>/head` which is unexpected.

In fact, I don't think we should be checking out `refs/pull/<PR_number>/merge` which doesn't even exist for the PR creator and may not contain the same code being proposed (but the code after merging).

I think I will create a composite action to make up for this

2022-03-01 10:57 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          password: ${{ secrets.DOCKER_PASS }}
We just used the names on CircleCI

2022-03-01 14:56 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +        uses: svenstaro/upload-release-action@v2
I did it for this one. However, I think we should be consistent and also do it for the github ones. Why treat those especially?

2022-03-01 15:11 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          # Otherwise, if we are currently on e.g. v1.6.1 and need to release v1.5.3, v1.5.3 will become latest.
I don't know how to solve this. There's https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#required-reviewers , but we are not really releasing to an environment.

I can't see anything in GitHub actions similar to CircleCI's `type: approval`

2022-03-01 16:30 UTC, leighmcculloch commented
> In fact, I don't think we should be checking out `refs/pull/<PR_number>/merge` which doesn't even exist for the PR creator and may not contain the same code being proposed (but the code after merging).

The intent behind this is not unique to GitHub Actions, other build systems work similar, the intent is to test the code that would result from the PR being merged. In this repo this maybe matters less in that we require branches to be up-to-date with master before they can be merged. Making the change in this PR further locks us into that I think. I don't have a problem with that, but something to be mindful.

2022-03-01 16:42 UTC, leighmcculloch reviewed
Couple asks, looking great though.

2022-03-01 16:42 UTC, leighmcculloch commented on .github/workflows/go.yml
> +        # is what github.ref points to)
Suggest giving a slightly less in the weeds description. When I read this I feel like it only makes sense to me because I have a lot of context already.
```suggestion
        # For pull requests, build and test the PR head not a merge of the PR with the destination.
```

2022-03-01 18:55 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          password: ${{ secrets.DOCKER_PASS }}
I don't see any high value in making them uniform either.

Since it was @jacekn who added the secrets, I will leave it up to him to rename it.

@jacekn let's do whatever you prefer, I am happy to adjust the code if you rename the secrets.

2022-03-01 19:03 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          # Otherwise, if we are currently on e.g. v1.6.1 and need to release v1.5.3, v1.5.3 will become latest.
I am confused. This is about preventing pushing to `stellar/horizon:latest` if the version being released is lower than the version which as already pointing `stellar/horizon:latest`

2022-03-01 19:04 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          # Otherwise, if we are currently on e.g. v1.6.1 and need to release v1.5.3, v1.5.3 will become latest.
But, now that I think about it, we could simply automate that.

2022-03-01 19:04 UTC, leighmcculloch commented on .github/workflows/horizon-release.yml
> +          password: ${{ secrets.DOCKER_PASS }}
Ah, @jacekn we already have these secrets in use on the stellar/quickstart repo at least. Given these credentials are going to be used on multiple repos, it might be worth defining them once as organization secrets that are enabled for use on these two repos and other repos we add, so that we have less secrets to track. (cc @brahman81 If you have thoughts.)

2022-03-01 19:05 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +        uses: docker/login-action@v1
> since any https://github.com/github action compromised probably has similar attack vectors to compromising the GitHub Action

I am not sure I agree with that, but sure!  I will pin them.

2022-03-01 20:26 UTC, leighmcculloch commented on .github/workflows/horizon-release.yml
> +          # Otherwise, if we are currently on e.g. v1.6.1 and need to release v1.5.3, v1.5.3 will become latest.
I think of something didn't need to be in Jenkins it is probably better here. cc @brahman81

2022-03-02 11:58 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          password: ${{ secrets.DOCKER_PASS }}
@jacekn friendly ping :)

2022-03-02 11:58 UTC, 2opremio commented on .github/workflows/horizon-release.yml
> +          # Otherwise, if we are currently on e.g. v1.6.1 and need to release v1.5.3, v1.5.3 will become latest.
The decision was to favor the Jenkins images since they are built with debian packages

2022-03-02 12:40 UTC, jacekn commented on .github/workflows/horizon-release.yml
> +          password: ${{ secrets.DOCKER_PASS }}
@2opremio apologies for the delay, I added 2 new variables now: `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`

2022-03-02 14:33 UTC, 2opremio commented
@leighmcculloch PTAL

2022-03-02 17:16 UTC, leighmcculloch approved these changes
🎉 The actions look good to me. I defer to @stellar/horizon-committers folks for the Horizon specifics.

2022-03-02 17:17 UTC, leighmcculloch requested changes

2022-03-02 17:17 UTC, leighmcculloch commented on .github/workflows/go.yml
> +        ref: ${{ github.head_ref || github.ref }}
@2opremio This change looks unnecessary now. It isn't used by the new actions. Do you need it still?

2022-03-02 17:18 UTC, leighmcculloch approved these changes

2022-03-02 17:18 UTC, leighmcculloch commented on .github/workflows/go.yml
> +        ref: ${{ github.head_ref || github.ref }}
Oh, I see, this is for consistency with the horizon verify range push.

2022-03-02 17:42 UTC, merged