exp/services/soroban-rpc: Add getTransactionStatus and sendTransaction json rpc methods
stellar/go pull request #4609
Opened 2022-09-26 13:37 UTC by tamirms

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Add json rpc methods for sending a transaction and querying a transaction status. This is implemented by proxying to the horizon txsub endpoint and the horizon transaction detail endpoint.

### Why

https://github.com/stellar/go/issues/4595
https://github.com/stellar/go/issues/4595

### Known limitations

* As a shortcut to save time ahead of meridian, we proxy transaction submissions to Horizon instead of submitting directly to captive core
* Pending transactions and transaction submission validation errors are stored in an memory data structure 
* I have not yet tested creating soroban smart contracts or invoking host functions because horizon does not support that functionality yet
* No websocket functionality implemented, so the client will need to poll the getTransactionStatus method

2022-09-26 14:16 UTC, tsachiherman requested changes
Overall looks good. Beside the notes added, I have one more request:
can you add a Stop()/Shutdown() that would cancel the context and block until all the child go routines are done ?
i.e. use sync/workgroup + child context so you could shut it down.
The goal here is to allow deterministic cleanup.

2022-09-26 14:16 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	return &TransactionProxy{
you might want to adjust the queueSize in case workers > queueSize.

2022-09-26 14:16 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	go p.startExpiryTicker(ctx)
I think that expiry ticker here is a bit of an overkill ( but functionally correct). you could easily prune the expired entries during SendTransaction. 
i.e. creating a go routine that is going to be idle most of the time isn't great.

2022-09-26 14:22 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.lock.RLock()
could you add a comment here -
// herr.Problem.Status == http.StatusNotFound
it was very tricky for me to figure this out by reading it.

2022-09-26 14:25 UTC, tsachiherman commented on exp/services/soroban-rpc/main.go
> +					cancel()
I think that you would want to call `cancel` after `handler.Close()`, since you don't want any request to go from the handler to the proxy *after* it's being canceled.

2022-09-26 14:30 UTC, tsachiherman commented on exp/services/soroban-rpc/main.go
>  					logger.Infof("Starting Soroban JSON RPC server on %v", port)
the port here should be pull from the actual TCP connection rather than the port argument.
Separately, could we consider changing the port into endpoint, for security reasons, and default it to "localhost:8000" ? that way, the end user can select the interface he would want to bind.

2022-09-26 16:51 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	Result *horizon.Transaction `json:"result"`
> Also, error handling here?

+1, if not a big stretch to populate `error` as optionally mentioned in the api docs, seems like could help diagnostics for clients.

2022-09-26 17:12 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	ID string `json:"id"`
> it should be an error TransactionStatusResponse

updated [send transaction api docs](https://stellarorg.atlassian.net/wiki/spaces/PJC/pages/4402151440/soroban-rpc+API+Docs#sendTransaction-(Meridian-or-use-Horizon)) to capture the behavior mentioned here, i.e. for `status` and `error` on the tx responses.

2022-09-26 17:43 UTC, tamirms commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	Result *horizon.Transaction `json:"result"`
ok I will try to follow that format but I will keep Result to have type `*horizon.Transaction` for now. Once we're able to submit soroban transactions through horizon I will update the `TransactionStatusResponse` to include the the smart contract return value. We will also need https://github.com/stellar/stellar-core/pull/3543 to be merged  to include the smart contract return value

2022-09-26 18:13 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +		return TransactionStatusResponse{
could p.deletePendingEntry(request.Hash) be done at this point as optimization, since tx status is known now, to keep the pending queue size down, rather than letting it wait longer for the expired loop to purge it.

2022-09-26 18:20 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.lock.Lock()
in general, and not suggesting for now, unless you saw value in it and not a stretch, has a context-aware lock been considered for usage, like `go-lock` with `tryLockWithContext(ctx)` just curious with advanced threading, potential for getting locked up and not honoring the callers ctx.

2022-09-26 18:37 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.lock.Lock()
@sreuland where do we have a use case where we use `tryLockWithContext` ? I'm familiar with the concept, but always found it too of a headache to implement.

2022-09-26 18:39 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction_test.go
> +		nil,
great test coverage btw, from this unit test layer, noticed may have been able to mock out `HTTP` in `horizonclient.Client`, and possibly exercise much of the new code paths, rather than system integration tests later, just thinking out loud, not suggesting change.

2022-09-26 18:47 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.lock.Lock()
I was thinking on ln 109, if there were a mis-matchted lock/unlock at some point, then ensuing caller requests would get stuck there on the `Lock()`, also if the caller defined a ctx with timeout shorter than the http client timeout(is configurable, I think is default of 10s) and passes that in here, could be another potential way that caller's context is ignored if the http response takes longer.

2022-09-27 13:18 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	Error  *problem.P `json:"error"`
could you add a code comment : 
// optional error in case status == error

2022-09-27 13:26 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +		p.wg.Add(1)
nit: you could have called
```golang
p.wg.Add(p.workers)
```
outside of the loop.

2022-09-27 13:27 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.cancel()
add code comments - 
```golang
// signal the worker go routines to abort
p.cancel()
// wait until the worker go routines are done
p.wg.Wait()
```

2022-09-27 13:31 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +			_, err := p.client.SubmitTransactionXDR(request.transactionXDR)
I'm surprised to see there is no context being passed to SubmitTransactionXDR; I would have expected to see that there is some sort of cancellation option.

2022-09-27 13:32 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +				p.deletePendingEntry(request.txHash)
if we did send the transaction successfully, don't we want to mark it as "success" ?

2022-09-27 13:34 UTC, tsachiherman commented on exp/services/soroban-rpc/main.go
> +	"github.com/stellar/go/network"
nit: move the the bottom import group.

2022-09-27 13:41 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	defer p.deleteExpiredEntries(time.Now())
I think it would be better to move this after taking the lock so that we won't take the lock twice within the function call.

2022-09-27 14:52 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	p.lock.Lock()
I generally agree with your observation here; as you've noted, in this case the lock is taken only for a short amount of time, and never for a blocking operation ( therefore, I can't see any concrete potential issue here )

2022-09-27 15:23 UTC, tamirms commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +			_, err := p.client.SubmitTransactionXDR(request.transactionXDR)
Yeah, I agree but the horizon client doesn’t support context passing. Otherwise I would have used it.

2022-09-27 15:25 UTC, tamirms commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	defer p.deleteExpiredEntries(time.Now())
Could you clarify what you are proposing? The delete expired entries function currently acquires a lock. Are you suggesting to remove the locking entirely and have the caller of the function responsible for the thread safety?

2022-09-27 15:38 UTC, tsachiherman commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	defer p.deleteExpiredEntries(time.Now())
sure. Move the defer call from line 107 to line 136, and remove acquiring the lock from within `deleteExpiredEntries`.

2022-09-27 16:45 UTC, sreuland commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +	defer p.deleteExpiredEntries(time.Now())
was curious why overall cache expiration purge is triggered here during request, could the purge be de-coupled from here and instead refactored as a timer loop started in `TransactionProxy.Start()` and stopped in `TransactionProxy.Close()` ?

2022-09-27 17:09 UTC, sreuland approved these changes
great approach and implementation to get this realized!

2022-09-27 18:12 UTC, tamirms commented on exp/services/soroban-rpc/internal/methods/transaction.go
> +				p.deletePendingEntry(request.txHash)
we don't want to store the successful response in the `results` map because horizon already will have the response available in its database.

That is why in `GetTransactionStatus()` the first thing we do is call `p.client.TransactionDetail(request.Hash)` which will query horizon for the response.

2022-09-27 18:32 UTC, tsachiherman approved these changes

2022-09-27 19:01 UTC, merged