LedgerChangeReader: Support State Expiration & Eviction
stellar/go pull request #4941
Opened 2023-06-30 12:52 UTC by paulbellamy

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Add LedgerCloseMetaV2 support to LedgerChangeReader.

### Why

So it emits correct changes for state expiration. Particularly:
- Entry extensions
- Entry evictions

This is to support: https://github.com/stellar/soroban-tools/pull/695

### Known limitations

[TODO or N/A]

2023-06-30 15:40 UTC, tsachiherman commented on ingest/ledger_change_reader.go
> +			r.ledgerCloseMeta.EvictedLedgerKeys(),
could you add an error case to `EvictedLedgerKeys` instead of ignoring the error coming back from `SetContractCode`/`SetContractData` ?

2023-06-30 15:50 UTC, tsachiherman requested changes
Few small requests.

2023-06-30 15:50 UTC, tsachiherman commented on ingest/ledger_change_reader_test.go
> +		assert.NotNil(t, change.Post, msg)
change
```golang
assert.NotNil(t, change.Post, msg)
```
to
```golang
require.NotNil(t, change.Post, msg)
```
since assert is going to continue with the execution, and the subsequent line would generate a segmentation fault.

2023-06-30 15:50 UTC, tsachiherman commented on ingest/ledger_change_reader_test.go
> +	// Check each change is what we expect
are the changes are always guaranteed to be in order ?

2023-06-30 15:50 UTC, tsachiherman commented on ingest/ledger_change_reader_test.go
> +	contractIdBytes, err := hex.DecodeString("df06d62447fd25da07c0135eed7557e5a5497ee7d15b7fe345bd47e191d8f577")
ST1003: var contractIdBytes should be contractIDBytes (stylecheck)

2023-06-30 15:50 UTC, tsachiherman commented on ingest/ledger_change_reader_test.go
> +	var contractId xdr.Hash
ST1003: var contractId should be contractID (stylecheck)

2023-06-30 15:50 UTC, tsachiherman commented on xdr/ledger_close_meta.go
> +		if l.MustV2().TxProcessing[i].TxApplyProcessing.V != 3 {
shouldn't this be applied only for the `LedgerCloseMeta.TxApplyProcessing` ?

2023-06-30 18:10 UTC, Shaptic commented on ingest/ledger_change_reader_test.go
> +		assert.NotNil(t, change.Post, msg)
we should `s/assert\./require.` in the whole repo, honestly - it rarely makes sense to continue a test after a failed assertion

2023-06-30 18:50 UTC, Shaptic reviewed
drive-by review :racing_car:

2023-06-30 18:50 UTC, Shaptic commented on ingest/change.go
> +			state.Data.SetContractData(&xdr.ContractDataEntry{
`golangci` says check your error and I think that's valid: this could help us catch places to update XDR in the future?

2023-06-30 18:50 UTC, Shaptic commented on ingest/change.go
> +			panic("Invalid LedgerEntry eviction type")
```suggestion
			panic(fmt.Errorf("Invalid LedgerEntry eviction type: %v", key.Type))
```

friendlier :) (might need an `import fmt`)

2023-06-30 18:50 UTC, Shaptic commented on ingest/ledger_change_reader.go
> +		r.state++
TIHI - should we just set the enum appropriately? :laughing:

2023-06-30 18:50 UTC, Shaptic commented on ingest/ledger_change_reader_test.go
> +		assert.Equal(t, extension, uint32(newExpiry-oldExpiry), msg)
protip: `assert.EqualValues` lets you ignore type differences :sunglasses:

2023-06-30 18:50 UTC, Shaptic commented on ingest/ledger_change_reader_test.go
> +		expectations[i](t, i+1, change)
clever!

2023-06-30 18:50 UTC, Shaptic commented on xdr/ledger_close_meta.go
> +		return nil
safe to do this over an empty slice?

2023-07-02 00:03 UTC, tsachiherman commented on xdr/ledger_close_meta.go
> +		return nil
Hmm. The answer is "it depends".
If it's just range iterations and appends, than it would work just fine.

However, if we were to have pointer receiver functions implemented on that slice, then it might be problematic.

2023-07-03 10:29 UTC, paulbellamy commented on ingest/ledger_change_reader_test.go
> +	// Check each change is what we expect
Yes. There isn't really a reason for them to be in any specific order, but the order is consistent due to the internal ledgerChangeReader implementation

2023-07-03 10:41 UTC, paulbellamy commented on ingest/ledger_change_reader.go
> +		r.state++
Probably yes, but this code generally needs a cleanup/refactor tbh.

2023-07-03 10:44 UTC, paulbellamy commented on xdr/ledger_close_meta.go
> +		return nil
Pointer methods on nil arrays work fine, afaik: https://go.dev/play/p/TOly3j6kQqy

Where it gets tricky is `encoding/json` treats them differently. So if clients have specific expectations about json structures it might be wrong.

2023-07-03 13:54 UTC, tsachiherman approved these changes

2023-07-03 14:06 UTC, merged