Ledger exporter packaging
stellar/go pull request #5254
Opened 2024-03-21 02:05 UTC by urvisavla

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

[TODO: Short statement about what is changing.]

### Why

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

2024-03-22 03:43 UTC, chowbao commented on exp/services/ledgerexporter/docker/Dockerfile
> +RUN apt-get update && apt-get install -y stellar-core=${STELLAR_CORE_VERSION}
Is there an advantage to doing an install of stellar-core?
For stellar-etl we kinda cheat and just use the image built from core/ops team
```
FROM stellar/stellar-core:20.2.0-1716.rc3.34d82fc00.focal

WORKDIR /etl

COPY --from=build /usr/local/bin/stellar-etl /usr/local/bin/stellar-etl
COPY --from=build /usr/src/etl/docker docker
```

2024-03-23 01:02 UTC, urvisavla commented on exp/services/ledgerexporter/docker/Dockerfile
> +RUN apt-get update && apt-get install -y stellar-core=${STELLAR_CORE_VERSION}
The only advantage I can think of is that we won't have to update our Dockerfile when the core gets an update.

2024-03-25 18:23 UTC, chowbao commented on exp/services/ledgerexporter/Makefile
> +VERSION ?= latest
Because we don't have a defined version we want to use right now. Would it make sense to push both a :latest and `git rev-parse --short HEAD` as a temporary way to version control?

2024-03-25 18:38 UTC, tamirms commented on exp/services/ledgerexporter/Makefile
> +docker-test:
I think this way of testing is fine for now. But, we may want eventually want to adopt the same integration testing style as horizon and soroban rpc where we setup a docker-compose file with the dependencies (in this case the fake gcs service) and launch the service in a go test. Once https://github.com/stellar/go/pull/5260 is merged, we can also rerun captive core over the same range and assert that the ledgers exported to the fake GCS service match what is returned by captive core.

2024-03-25 18:42 UTC, tamirms approved these changes
I agree with @chowbao's comment for including the git sha in the docker image tag. Apart from that, this looks good!

2024-03-25 18:49 UTC, sreuland commented on exp/services/ledgerexporter/Makefile
> +	cd ../../../ && \
minor, could do the directory change to set initial docker context path once before `ifndef`

2024-03-25 18:50 UTC, sreuland commented on exp/services/ledgerexporter/Makefile
> +	$(SUDO) docker run -d --name fake-gcs-server -p 4443:4443 \
nice!

2024-03-25 19:12 UTC, sreuland commented on exp/services/ledgerexporter/docker/start
> +if [[ -n "$START" || -n "$END" ]]; then
could this script just pass all parameters to ledgerexporter bin and let [validateAndSetLedgerRange()](https://github.com/urvisavla/go/blob/ledger-exporter-packaging/exp/services/ledgerexporter/internal/config.go#L88) sort it out and report error if needed, rather than replicate similar validation in this layer also?

2024-03-25 19:14 UTC, sreuland approved these changes
nice addition, left minor comments for consideration.

2024-03-25 21:41 UTC, chowbao approved these changes

2024-03-26 00:18 UTC, urvisavla commented on exp/services/ledgerexporter/docker/start
> +if [[ -n "$START" || -n "$END" ]]; then
Good point. Done.

2024-03-26 00:18 UTC, urvisavla commented on exp/services/ledgerexporter/Makefile
> +	cd ../../../ && \
Done.

2024-03-26 00:18 UTC, urvisavla commented on exp/services/ledgerexporter/Makefile
> +VERSION ?= latest
Done.

2024-03-26 09:29 UTC, jacekn requested changes
This will create divergence and inconsistency between how horizon is being build and published and how ledgerexporter would be. For horizon we support both debs and docker images to ease of deployment and I think we should be consistent that that approach given that one day we'll ask people to replace their full history horizon with ledgerexporter.
Ledgerexporter is a golang app so it's super easy to use build process consistent with horizon, I can help you with that.

2024-03-26 09:47 UTC, jacekn commented
@urvisavla something else I wanted to add - this PR would make it impossible to people to cryptographically verify binaries coming from SDF. This is one of the big security wins of deb packages and this benefit propagates to docker images build from those debs. For smaller projects we accepted the security tradeoff but for something at the core of ingestions, such as this project, this tradeoff might be unacceptable.

2024-03-26 14:10 UTC, mollykarcher commented
> this PR would make it impossible to people to cryptographically verify binaries coming from SDF

@jacekn can you tell me more about this? As in, is this possible today and how? We actually have a couple partners (at minimum, Coinbase and Circle) that have chosen not to use our debian packages (and instead build from source), due to their own internal compliance standards and not wanting to use pre-built binaries.

2024-03-26 22:14 UTC, urvisavla commented
> This will create divergence and inconsistency between how horizon is being build and published and how ledgerexporter would be. For horizon we support both debs and docker images to ease of deployment and I think we should be consistent that that approach given that one day we'll ask people to replace their full history horizon with ledgerexporter. Ledgerexporter is a golang app so it's super easy to use build process consistent with horizon, I can help you with that.

That's a valid concern. The deb package is absent in this PR because this is the first iteration and it will be added in a [later iteration.](https://stellarorg.atlassian.net/browse/HUBBLE-369) We can update the Dockerfile later to install from the deb package instead of building it from source. 

The reason the deb package is not implemented in the first iteration is because we're prioritizing the creation of a Docker image and putting it somewhere the data team can access and use it to test it. This is defined in the [ticket](https://stellarorg.atlassian.net/browse/HUBBLE-270). 

>Something else I wanted to add - this PR would make it impossible to people to cryptographically verify binaries coming from SDF. This is one of the big security wins of deb packages and this benefit propagates to docker images build from those debs. For smaller projects we accepted the security tradeoff but for something at the core of ingestions, such as this project, this tradeoff might be unacceptable.

If security around building from source in the first iteration is a major concern, can we push the image to a private registry for internal use only? This may allow us to make progress without publishing it to the public registry.

2024-03-27 10:17 UTC, jacekn commented on exp/services/ledgerexporter/docker/start
> +#! /usr/bin/env bash
This wrapper adds complexity and will require maintenance. I think would be good to remove it and instead just call ledgerexporter directly for simplicity.

With this wrapper it's not easy to add arguments to the ledgerexporter call - users would need to bypass the script completely and use custom entrypoint but this requires deeper understanding of how the image is constructed.
Also part of the script's functionality is to render config on disk from env variables. This normally isn't necessary in docker or k8s world - it's very easy to consume configs both with docker and in k8s (via ConfigMaps). Rendering config like this also means that support for every new config option needs to be baked into the image before those options can be used which would add maintenance burden. On top of that users who decide to use ConfigMaps in k8s will see the entrypoint try to write data to the config.toml file which might clash with the location for the config they choose.

The wrapper does two main things:
1. It passes arguments to the ledgerexporter call
2. It renders config
 
To address point 1 we should be able to rely on docker and k8s directly. Both make it very easy to pass arguments to the images. For example with the horizon image the following work as expected:
```
docker run stellar/stellar-horizon:stable --help
docker run stellar/stellar-horizon:stable version
```

We should be able to make the following work with the ledgerexporter image:
```
docker run stellar/ledgerexporter --start 10 --end 20
```

I can think of two solutions to address item 2.
First option is to just rely on users providing config. In k8s we'd require this via ConfigMap and for docker using volume mount. This will require no changes to ledgerexporter at all.

If we want to add flexibility we could also update ledgerexporter to allow it to consume environment variables thus not require config at all. We only set the following: `NETWORK` , `ARCHIVE_TARGET`, `ledgers_per_file` and  `files_per_partition`. If we do this we will of course still retain capability to use ConfigMaps so this would be completely optional method.

2024-03-27 10:19 UTC, jacekn commented
> > This will create divergence and inconsistency between how horizon is being build and published and how ledgerexporter would be. For horizon we support both debs and docker images to ease of deployment and I think we should be consistent that that approach given that one day we'll ask people to replace their full history horizon with ledgerexporter. Ledgerexporter is a golang app so it's super easy to use build process consistent with horizon, I can help you with that.
> 
> That's a valid concern. The deb package is absent in this PR because this is the first iteration and it will be added in a [later iteration.](https://stellarorg.atlassian.net/browse/HUBBLE-369) We can update the Dockerfile later to install from the deb package instead of building it from source.

Thank you for context, this sounds fair to me. I can also see that the Dockerfile is Ubuntu based which will make it easy to switch method of binary install.

I added a few more comments. If we use different binary path we will be able to make it even easier to switch to debs in the future because path wouldn't change.

I also added comment about the `start` wrapper, I think we may be able to remove it to simplify the image.

2024-03-27 22:15 UTC, jacekn commented on exp/services/ledgerexporter/docker/start
> +#! /usr/bin/env bash
> We haven't yet implemented the "CLI" yet, which will include both the command line flags as well as environment variables to configure the Ledger Exporter, similar to how it's done in Horizon. Here is the [ticket](https://stellarorg.atlassian.net/browse/HUBBLE-271) for that.
> 
> The start script has been added to simplify testing the image for the team so that they can specify the configuration like the `NETWORK` and `ARCHIVE_TARGET` without hardcoding them or manually modifying the container's config file, until the CLI/config is ready.

Could you describe workflow that you think will be used during testing? I'm wondering if there are some assumptions I'm making because I _think_ using config file should be very simple. If you create `./config/config.toml` then something like this should work:
```
docker run -v ./config:/etc/ledgerexporter/ stellar/ledgerexporter --start 10 --end 20
```

if you use env variables you presumably need to run something like this:
```
docker run --env-file ./settings.env stellar/ledgerexporter
```

In either case there is no need to hardcode anything or modify anything inside container when settings change.

The only difference I can see is that the first method doesn't allow you to edit config on the fly using env variables passed as docker CLI flags but this can be easily achieved using simple wrapper script run outside of docker. In fact you should be able to take the `start` script and modify it to write config on disk before running docker to achieve the same result without baking this logic inside the image.
This way you'd keep the docker image closer to best practices and there would be no need to modify it when ledgerexporter CLI is changed.

> Regarding configuration options, we're also planning to add additional command line options such as 'resume.' Plus, we'll be adding configuration options to set up captive-core in the traditional manner, using settings like `CAPTIVE_CORE_CONFIG_PATH` and `CAPTIVE_CORE_BINARY_PATH` instead of relying on the default configuration associated with the "NETWORK" parameter. Here is the [ticket](HUBBLE-278: https://stellarorg.atlassian.net/browse/HUBBLE-27) for that.
> So while we currently have a basic CLI that takes `start` and `end` parameters from the command line which will allow a command like `docker run stellar/ledgerexporter --start 10 --end 20`, I'd rather hold off on making changes until we have completed the CLI/config implementation. It might be more efficient to implement all the changes at once.

So what I'm proposing means that you will not have to change the image at all when you make CLI changes to ledgerexporter. The only place where you'd be adding/changing/removing flags would be the ledgerexporter itself.
If it starts using env variables natively then you'll be able to pass those to the container and they'll be available for ledgerexporter to read and act on. If you add new CLI flags you'll be able to pass them to the image without need to change any wrappers:
```
docker run -v ./config:/etc/ledgerexporter/ stellar/ledgerexporter --start 10 --end 20 --new-flag foo
# or
docker run -v ./config:/etc/ledgerexporter/ stellar/ledgerexporter resume
```
if you change any default values for CLI flags those will take effect as soon as you rebuild the image without the need to edit the `start` wrapper. For the most part the Docker packaging config will become maintenance free, you'll only have to worry about ledgerexporter itself.

2024-03-27 22:51 UTC, urvisavla commented on exp/services/ledgerexporter/docker/start
> +#! /usr/bin/env bash
Once the cli is complete, the config file and the start script won't be needed anymore. The current method of wrapping the config is simpler for testing purpose because it doesn't require the data team to be familiar with the config file format.  Also, once the "start" is removed, there is no other way to run the container than by providing ledger exporter command line parameters in the docker run command.

2024-03-28 15:45 UTC, jacekn approved these changes

2024-03-28 15:45 UTC, jacekn commented on exp/services/ledgerexporter/docker/start
> +#! /usr/bin/env bash
> Once the cli is complete, the config file and the start script won't be needed anymore. The current method of wrapping the config is simpler for testing purpose because it doesn't require the data team to be familiar with the config file format.

Maybe we could help the data team get up to speed on the config format? I'd be happy to help @sydneynotthecity out with this if this. The format is very simple so hopefully it won't take long.

Another option I can think of to avoid baking custom wrappers in this repo would be to build standard image here and have the data team build their own based on one from this repo. They should be able to start with `FROM stellar/ledgerexporter:latest` and add custom wrapper on top with minimal effort. I can also help with that if needed.

> Also, once the "start" is removed, there is no other way to run the container than by providing ledger exporter command line parameters in the docker run command.

Yes this is great. I was thinking that if we do it in this PR then there will be no need to change anything when you update ledgerexporter

2024-03-28 20:21 UTC, urvisavla commented on exp/services/ledgerexporter/docker/start
> +#! /usr/bin/env bash
@jacekn, The team discussed this during our standup today and prioritized addressing these concerns. Since I'll be on vacation for the next couple of weeks, I'll merge this PR for now but I have created a [ticket](https://stellarorg.atlassian.net/browse/HUBBLE-369) to address these and will resume work on this as well as implementing CLI after I return. Thanks!

2024-03-28 20:24 UTC, merged